In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [35]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data",
                names = ['buy','maint','doors','persons','lug_boot','safety','car'])
df.head()

buy  maint doors persons lug_boot safety    car
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [36]:
print(df['doors'].unique())

['2' '3' '4' '5more']


In [37]:
cad = {'unacc':1, 'acc':2, 'vgood':3, 'good':4}
cd = {'5more' : 5, '2':2, '4':4, '3':3 }
cp = {'more':5, '2':2, '4':4}

In [38]:
df['car'] = df['car'].map(cad)
df['doors'] = df['doors'].map(cd)
df['persons'] = df['persons'].map(cp)

In [39]:
from sklearn.preprocessing import LabelEncoder

In [40]:
X = pd.concat([pd.get_dummies(df[['buy','maint','lug_boot','safety']],drop_first=True), df[['doors','persons']]], axis=1).values

In [41]:
X

array([[0, 0, 1, ..., 0, 2, 2],
       [0, 0, 1, ..., 1, 2, 2],
       [0, 0, 1, ..., 0, 2, 2],
       ...,
       [1, 0, 0, ..., 0, 5, 5],
       [1, 0, 0, ..., 1, 5, 5],
       [1, 0, 0, ..., 0, 5, 5]], dtype=int64)

In [42]:
y = df['car'].values
y

array([1, 1, 1, ..., 1, 4, 3], dtype=int64)

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
from sklearn.preprocessing import StandardScaler

In [89]:
ss = StandardScaler()

In [90]:
ss.fit_transform(X_train)
ss.transform(X_test)

C:\Users\visha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\visha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\visha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.58124945, -0.58793451, -0.56899454, ..., -0.70403906,
         0.44902478, -1.3577004 ],
       [-0.58124945,  1.7008697 , -0.56899454, ...,  1.42037574,
        -1.33673708,  0.25774683],
       [-0.58124945, -0.58793451, -0.56899454, ...,  1.42037574,
         1.34190571, -1.3577004 ],
       ...,
       [-0.58124945,  1.7008697 , -0.56899454, ..., -0.70403906,
        -1.33673708,  1.06547044],
       [-0.58124945, -0.58793451,  1.7574861 , ..., -0.70403906,
         1.34190571,  1.06547044],
       [-0.58124945,  1.7008697 , -0.56899454, ...,  1.42037574,
        -1.33673708, -1.3577004 ]])

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
from sklearn.linear_model import LogisticRegression

In [93]:
lr = LogisticRegression(C=30, penalty='l1')

In [100]:
lr.fit(X_train,y_train)

C:\Users\visha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\visha\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=30, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l1', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [95]:
y_pred = lr.predict(X_test)

In [96]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [97]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.91      0.96      0.94       235
           2       0.74      0.66      0.70        83
           3       0.93      0.76      0.84        17
           4       0.36      0.36      0.36        11

   micro avg       0.86      0.86      0.86       346
   macro avg       0.74      0.69      0.71       346
weighted avg       0.86      0.86      0.86       346



In [98]:
print(accuracy_score(y_test,y_pred))

0.861271676300578


In [99]:
print(confusion_matrix(y_test,y_pred))

[[226   9   0   0]
 [ 21  55   0   7]
 [  0   4  13   0]
 [  0   6   1   4]]
